### ISSUE TITLE
NullPointerException when adding to database

### ISSUE THREAD

**Issue by Glurt** [requery/requery#109]
I'm getting the following exception when adding some new entities to the database:

> java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Class.isInterface()' on a null object reference

There's no stacktrace so I can't track down where it's coming from but it seems to be one of the values being null, is it necessary for every value being added to have a value or is null acceptable?

**Comment by Glurt** [comment]
Ok to give some more information, I've added the following variable to an Entity

````
@ManyToMany
Set<AbstractSubreddit> subreddits;
````

With Abstract Subreddit looking like:
````
@Entity
public abstract class AbstractSubreddit {
 String display_name = "";
}
````

I've also managed to get a stack trace, I'll keep doing some digging but it's pretty much trial and error.

> Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Class.isInterface()' on a null object reference
                                                                          at java.lang.Class.isAssignableFrom(Class.java:1286)
                                                                          at io.requery.util.ClassMap.findKey(ClassMap.java:57)
                                                                          at io.requery.util.ClassMap.get(ClassMap.java:86)
                                                                          at java.util.Collections$UnmodifiableMap.get(Collections.java:1268)
                                                                          at io.requery.meta.ImmutableEntityModel.typeOf(ImmutableEntityModel.java:50)
                                                                          at io.requery.sql.EntityWriter.updateAssociations(EntityWriter.java:663)
                                                                          at io.requery.sql.EntityWriter.insert(EntityWriter.java:450)
                                                                          at io.requery.sql.EntityWriter.upsert(EntityWriter.java:491)
                                                                          at io.requery.sql.EntityDataStore.upsert(EntityDataStore.java:249)
                                                                          at io.requery.rx.SingleEntityStoreFromBlocking$6.get(SingleEntityStoreFromBlocking.java:130)
                                                                          at io.requery.rx.SingleOnSubscribeFromSupplier.call(SingleOnSubscribeFromSupplier.java:34)
                                                                          at io.requery.rx.SingleOnSubscribeFromSupplier.call(SingleOnSubscribeFromSupplier.java:23)

**Comment by npurushe** [comment]
Probably in your @ManyToMany definition you want to use the generated class Subreddit and not the abstract one, that should fix the error. But looks like this exception can be handled.

**Comment by Glurt** [comment]
Ok I've changed it to 

````
@ManyToMany
Set<AbstractSubreddit> subreddits;
````

But I'm still getting the same exception, it seems that the referencedClass value in the Account.subreddits Attribute isn't being set. I'll see if I can figure out why.

**Comment by npurushe** [comment]
This can happen if you don't have a @ManyToMany defined in the AbstractSubreddit class. For a many to many relationship the referenced class is set to a generated join entity that bridges the two, so it needs to be defined on both sides. There is an [example](https://github.com/requery/requery/blob/master/requery-test/src/main/java/io/requery/test/model/AbstractPerson.java#L62) in the test code, look at both Person & Group.

**Comment by Glurt** [comment]
That makes sense actually, I've made changes based on the example. AbstractAccount now has:

````
@ManyToMany(mappedBy = "subscribers")
 Set<Subreddit> subreddits;
````

AbstractSubreddit now has:
````
@JunctionTable(name = "Subreddit_Subscribers")
@ManyToMany
Set<Account> subscribers;
````
and now I'm getting 

> Caused by: java.lang.NullPointerException
                                                                            at io.requery.util.Objects.requireNotNull(Objects.java:36)
                                                                            at io.requery.cache.WeakEntityCache$WeakReferenceMap.putValue(WeakEntityCache.java:62)
                                                                            at io.requery.cache.WeakEntityCache.put(WeakEntityCache.java:106)
                                                                            at io.requery.sql.EntityWriter.insert(EntityWriter.java:456)
                                                                            at io.requery.sql.EntityWriter.cascadeSave(EntityWriter.java:898)
                                                                            at io.requery.sql.EntityWriter.updateAssociations(EntityWriter.java:694)
                                                                            at io.requery.sql.EntityWriter.insert(EntityWriter.java:450)
                                                                            at io.requery.sql.EntityWriter.upsert(EntityWriter.java:491)
                                                                            at io.requery.sql.EntityDataStore.upsert(EntityDataStore.java:249)
                                                                            at io.requery.rx.SingleEntityStoreFromBlocking$6.get(SingleEntityStoreFromBlocking.java:130)
                                                                            at io.requery.rx.SingleOnSubscribeFromSupplier.call(SingleOnSubscribeFromSupplier.java:34)
                                                                            at io.requery.rx.SingleOnSubscribeFromSupplier.call(SingleOnSubscribeFromSupplier.java:23) 

I appreciate you helping me with all this, perhaps this could be part of the FAQ.

**Comment by npurushe** [comment]
That can be resolved by placing a @Key in the class being persisted, generally a key is required for all types being cached. I will aso provide a better error instead of a NPE

**Comment by Glurt** [comment]
Both AbstractAccount and AbstractSubreddit extend from Thing

````
@Superclass
public abstract class Thing implements Persistable {

    @Key
    public String id;

    @Column(unique = true)
    public String name;
    @Column
    public DateTime created;
    @Column
    public DateTime created_utc;
}
````

Is this likely to be the cause of the issue?

**Comment by npurushe** [comment]
That should be fine, looks like you haven't set a key value then so its null. That would cause the exception.

**Comment by Glurt** [comment]
Looks like you were right, the dummy item I was inserting had no key.

It's almost working now, I've managed to play around with CascadeActions to get it working but I have a couple more questions before I close this issue.

1. Can you explain @JunctionTable, what it does and how you decide which class defines it in a ManyToMany relationship?

2. Same again with CascadeActions, I was using the default SAVE but it was trying to update the Subreddit instead of insert so I've set it to NONE. What I would like is to add an Account along with it's Subreddits, if any the Account or any of its Subreddits already exist then update. If an Account is removed then only the Subreddits that are not linked to another Account are removed as well. Is this possible?

3. And finally, is it possible to have a String @Key, if so why is the generated Join Table Key an Integer?

**Comment by npurushe** [comment]
Glad it's almost there,

1. @JunctionTable can be placed on either side of a @ManyToMany it just defines which table name is placed first in the generated entity, but that is configurable as well

2. The cascade actions are about what to do with the changed entities of a parent entity when it is inserted/updated/deleted. Currently it can't perform more complex actions then just inserting/updating/deleting. but Cascade upsert may help this case and this is being added soon.

3. Currently it is generated as an Integer by default But I agree it should automatically use the key type of the source entity. So I will add this in the next update.
