### ISSUE TITLE
Cascade Save cause constraint violation

### ISSUE THREAD

**Issue by rafoufoun** [requery/requery#65]
I have this relation between 2 of my entities : 

```
@Entity
public abstract class AbstractNewsArticle extends StreamItem {

    @Key
    String id;
    String title;
    String content;

    @OneToMany(mappedBy = "article", cascade = {CascadeAction.DELETE, CascadeAction.NONE})
    Set<Image> imageSet;
}
```

and 

```
@Entity
public abstract class AbstractImage {

    @Key
    @Generated
    int id;

    @ManyToOne
    NewsArticle article;

    String path;
    String caption;
}
```

Updating my NewsAticle (with dataStore.update(article)) cause a cascadeSave on the Image entities, which tries to insert a new NewsArticle with the same id, causing a constraint violation (primary key).

The Exception is thrown in EntityUpdateOperation.java method execute(final QueryElement<Scalar<Integer>> query)

**Comment by npurushe** [comment]
Hi did you mean it tries to insert an Image with a new id? or the article. Is the article in your image the same one as contains the image (eg. bidirectional) ? Also if you can provide the stacktrace that will be great thanks!

**Comment by rafoufoun** [comment]
Hi,

It seems that it tries to insert a new article : 

`io.requery.PersistenceException: java.sql.SQLIntegrityConstraintViolationException: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: NewsArticle.id (code 1555)`

**Comment by npurushe** [comment]
Hi does your stack trace have `EntityWriter.cascadeSave` in it? hard to tell from only the first line, just want to confirm is from cascading the article belonging to the image and not from updating the key of the article.

**Comment by rafoufoun** [comment]
You can see the methods stacktrace here when I put the breakpoint into the catch clause of the execute() method : 
![capture d ecran 2016-04-01 a 09 24 45](https://cloud.githubusercontent.com/assets/7149611/14200535/d1be7dae-f7eb-11e5-8055-d18a8bbc9d89.png)


Then the variables values into the cascadeInsert (which you can see in the previous image) : 

![capture d ecran 2016-04-01 a 09 25 31](https://cloud.githubusercontent.com/assets/7149611/14200541/e9c9914a-f7eb-11e5-82b3-ae457aff4864.png)

The cascadeSave calls cascadeInsert on the NewsArticle, then the constraint violation is thrown.

If you need more informations do not hesitate :)

**Comment by npurushe** [comment]
Hi thanks that helps a lot. So this is happening because because isLinked() is false for your entity so it choses to insert instead of update. How was that NewsArticle created? From a query or programmatically? If programmatically that would explain the problem. I think instead of just isLinked it can be changed to check for key presence as well which should fix your problem.

**Comment by rafoufoun** [comment]
This NewsArticle is created programatically, items are fetched from a webservice, then parsed into NewsArticles (as well as the Image set). 
Yep maybe check the key presence is a good solution, if we can assure that 0 is the non-presence.

Hope it helps ! Thanks for the great lib by the way

**Comment by npurushe** [comment]
Sure that helped a lot, should be an updated build tomorrow with a fix. Thanks for reporting

**Comment by rafoufoun** [comment]
Hi,

I've updated requery to beta11 and I still have the issue : 
![capture d ecran 2016-04-04 a 10 20 30](https://cloud.githubusercontent.com/assets/7149611/14241987/0bfb22a0-fa4f-11e5-81a8-5fa7e0f50b61.png)

As you can see on the screenshot :

- The method succession : 
    - I call update() on my NewsArticle
    - Then updateAssociation() is called to store the Image entity
    - Then updateInverseAssociation() to save the NewsArticle, cascadeSave() and insert()

You can see the variable value, the cascadeInsert(referenced) is called on the NewsArticle.

**Comment by npurushe** [comment]
Ah sorry that didn't solve it. What's the state of the key(s) in your NewsArticle entity? Are the keys having the `PropertyState` value of MODIFIED or LOADED? I will try to replicate your case today.

**Comment by rafoufoun** [comment]
Here you have the attribute's values : 
![capture d ecran 2016-04-04 a 16 12 28](https://cloud.githubusercontent.com/assets/7149611/14250745/1a94abde-fa80-11e5-9a80-efd522d69ae9.png)

**Comment by npurushe** [comment]
Hi thanks for the detailed report, I've made a change that I think should solve it but will do a bit more testing tomorrow before releasing in a new update.

**Comment by npurushe** [comment]
Please retry with the beta12 version

**Comment by rafoufoun** [comment]
I've tried with beta12 and still have the issue. 

I've checked your modifications and can tell you that inside the newly introduced cascadeSave(referenced, null), the writer.insert is called.
![capture d ecran 2016-04-07 a 09 57 46](https://cloud.githubusercontent.com/assets/7149611/14344320/3757ac2a-fca7-11e5-9e50-fca5636fdbff.png)

Then, cascadeInsert(referenced) is called on the NewsImage (EntityWriter.java line 435).

Maybe the issue is coming from the way I want to insert my entities:
- the NewsArticle entities have ids coming from a webservice, but Images have not. So in order to avoid inserting multiple times the same image through several refreshs, I delete all the images associated with a NewsArticle before updating this article. Then the update will insert the Image Set, maybe the issue is here.
Given that the Images are inserted and not updated, requery try to insert the associated NewsArticle (which already exists)

**Comment by npurushe** [comment]
I would check that the NewsArticle associated with the Image is the same as the NewsArticle that you are inserting. If they are not the same that would explain your problem. In the break point you are showing in your screenshot the NewsArticle there must not have any id set which is why it is going into insert and not update.

**Comment by rafoufoun** [comment]
You can check this simple project that I made. It reflects the issue I'm having.
[RequerySample.zip](https://github.com/requery/requery/files/212489/RequerySample.zip)

**Comment by npurushe** [comment]
Thanks! will look

**Comment by npurushe** [comment]
Thanks that helped a lot, working on a fix

**Comment by npurushe** [comment]
Thanks for your patience on this! will post an updated build with the change tomorrow

**Comment by npurushe** [comment]
Please try the updated beta14 version

**Comment by rafoufoun** [comment]
beta14 solved the issue :)

**Comment by npurushe** [comment]
Awesome! glad to hear that

**Comment by VincentMolinie** [comment]
I'm having the same issue and I'm on master. But it's really strange cause It's seems to be random, I juste get the exception sometimes. 

```java
@Entity
public abstract class AbstractPerson {
    @Key
    String uuid;

    String username;
}

@Entity
public abstract class AsbtractChat {
    @Key
    String uuid;

    @ManyToOne
    Person user;

    @ManyToOne
    Person otherUser;
} 
```

When I try to create a chat and insert it sometimes I get this exception. The person models are both inserted before the chat and normally up to date. But when I try to create the chat it tries to insert one of them. Why ?
