### ISSUE TITLE
Working with existing database throws TableModificationException.

### ISSUE THREAD

**Issue by MisterWeeMan** [requery/requery#856]
`RequeryDocument` class:

``` Kotlin
@Entity
@Table(name = "ipad_docs_media")
data class RequeryDocument (

        @get:Key
        @get:Generated
        @get:Column(nullable = false)
        val id_media: Int,

        @get:Column(length = 32, nullable = false)
        val type: String = "",

        @get:Column(length = 255, nullable = false)
        val icon: String = "",

        @get:Column(length = 255, nullable = false)
        val name: String = "",

        @get:Column(length = 255, nullable = false)
        val description: String = "",

        @get:Column(length = 255, nullable = false)
        val file: String = "",

        val multimedia: String?,

        @get:Column(nullable = false)
        val cansend: Int = 1,

        @get:Column(length = 64, nullable = false)
        val entity_id: String,

        val date_modification: Date,

        @get:Column(nullable = false)
        val record_status: Int = 1

)
```

Test class:
``` Kotlin
class RemoteDocumentsSourceImplTest {

    // a rule do something before a test method is run
    @get:Rule
    val tempFolder: TemporaryFolder = TemporaryFolder()

    init {
        Timber.plant(Timber.DebugTree())
    }

    @Test
    fun getList(){

        val file = getAssetAsFile("db/docs_test.sqlite", tempFolder.root)

        val databaseSource = DatabaseSource(
                InstrumentationRegistry.getContext(),
                Models.DEFAULT,
                file.absolutePath,
                1
        )
        val entityDataStore = KotlinEntityDataStore<RequeryDocument>(databaseSource.configuration)

        val listReqDoc = entityDataStore {
            val query = select(RequeryDocument::class) orderBy RequeryDocument::name.lower()
            query.get().collect(ArrayList<RequeryDocument>())
        }

        Timber.d(listReqDoc.size.toString())
    }
}
```

Throws 
```
io.requery.sql.TableModificationException: java.sql.SQLException: android.database.sqlite.SQLiteException: table ipad_docs_media already exists (code 1 SQLITE_ERROR): , while compiling: create table ipad_docs_media (id_media integer primary key autoincrement not null, cansend integer not null, date_modification date, description varchar(255) not null, entity_id varchar(64) not null, file varchar(255) not null, icon varchar(255) not null, multimedia varchar(255), name varchar(255) not null, record_status integer not null, type varchar(32) not null)
```

**Comment by MisterWeeMan** [comment]
Resolved. It wasn't a problem with Requery.

**Comment by RiccardoM** [comment]
For anyone still having this problem, I've found a solution to it. 

First of all, we need to know that Requery can access only the SQLite databases that are placed inside the proper folder, which is the `databases` folder inside the internal application data folder. 

That being said, the following code works properly: 

```kotlin
val dbFile = context.getDatabasePath(databaseName)

// Delete any existing database file
if (dbFile.exists()) {
    dbFile.delete()
}

// Now you can use the dbFile variable (of type File) to do whatever you want, even copy your existing database here

// After copying the existing database to this location, call the following
DbOpenHelper(context, databaseName).initDatabase()
```

The `DbOpenHelper` class is defined as follows

```kotlin
internal class DbOpenHelper(context: Context, dbName: String): SQLiteOpenHelper(context, dbName, null, 1) {
    override fun onCreate(db: SQLiteDatabase?) {}
    override fun onUpgrade(db: SQLiteDatabase?, oldVersion: Int, newVersion: Int) {}

    fun initDatabase() {
        readableDatabase
        close()
    }
}
```

Please note that without the last line, the database won't be properly accessible. This is due to the fact that in order to be opened properly inside Android, an SQLite database must have the `android_metadata` table inside it. The `initDatabase` method does exactly this: it opens a readable database that creates that table and immediately closes it to allow usages from other places of the same file.
